@baseUrl = http://localhost:5000

### Create PIX payment
POST {{baseUrl}}/payments/pix
Content-Type: application/json

{
  "value": 1500
}

### Confirm PIX payment
POST {{baseUrl}}/payments/pix/confirmation
Content-Type: application/json

{
  "value": 500,
  "bank_payment_id": "6dee6192-84e8-49c2-b93c-cc01a1dd442f"
}

### Get PIX payment
GET {{baseUrl}}/payments/pix/1
Accept: text/plain

### Get QR code image
GET {{baseUrl}}/payments/pix/qr_code/qr_code_payment_c5fb8b9f-af91-431a-be35-9f7461acc313